### ISSUE TITLE
ability to have wild cards in urls

### ISSUE THREAD

**Issue by tansaku** [oesmith/puffing-billy#146]
we're doing some stripe caching with puffing billy but we're noticing an issue with developers with different browser encodings:

https://checkout.stripe.com/v3/data/locales/en_gb-TXHkb1MWMa7xOQfCZf1DFA.json

vs

https://checkout.stripe.com/v3/data/locales/en_us-Q8sb44xKqXQ36SyFw0avQ.json

is there some way to have billy respond with the same cached result given that a URL starts with a particular prefix, e.g. 

https://checkout.stripe.com/v3/data/locales

or using a wild card like so:

https://checkout.stripe.com/v3/data/locales/*.json

Many thanks in advance

**Comment by tansaku** [comment]
ah, or perhaps they already support regex?

**Comment by tansaku** [comment]
hmm, seems like regexes might work for proxies, but we're trying to coordinate with the cache.  We tried the following step:

```ruby
Given(/^I have a locale independent puffing billy proxy$/) do
  response = YAML.load(File.open(Billy::Cache.instance.cache_file('get_checkout.stripe.com_6713a31ecd1a1a2e8dbd48f9a2c35bce741f1acf')))[:content]
  proxy.stub('/https\:\/\/checkout\.stripe\.com\/v3\/data\/locales\/.*\.json/').and_return(response)
end
```

but that didn't seem to help - we're going to fall back on checking in multiple locale files for the moment until we can find a better way ...

**Comment by ronwsmith** [comment]
Those are distinct URLs and likely have very different content.  I would personally want to have them both cached separately.  I don't see a big disadvantage of having many cache files -- it should be set it and forget it.

**Comment by tansaku** [comment]
It would be great to set and forget, but it means that each developer in a new locale needs to understand how to get the the new locale file cached.  In this case with stripe they have to copy the contents of the other locale file over - it's tricky.  

I have found this in the puffing billy settings though:

```
c.merge_cached_responses_whitelist = [/https\:\/\/checkout\.stripe\.com\/v3\/data\/locales\/.*\.json/]
```

which might be the fix we need ...?

**Comment by ronwsmith** [comment]
If developers in new locales have caching enabled it would simply fetch it from stripe the first time and they'd just need to commit that new cache file.  Not sure if I'm missing something since I don't use stripe.

That fix looks good to me.  If that's working for you, please close this issue.  Thanks!

**Comment by tansaku** [comment]
That fix doesn't seem to work as expected, but we seem to have things covered ...

**Comment by ndbroadbent** [comment]
I finally figured this out. I looked at the test logs, and HTTPS URLs all have port `:443`, which is why my stubs weren't matching. I ended up doing this monkey patch to get things working:

```ruby

module Billy
  class Cache
    def self.find_post_response(url)
      Dir.glob("#{Billy.config.cache_path}/*.yml").each do |file|
        response = YAML.load_file(file)
        if response[:method] == 'post' && response[:url] == url
          return response
        end
      end
    end
  end

  def self.stub_cached_post(url, proxy)
    return unless response = Billy::Cache.find_post_response(url)
    # Stub URL does not match without port 443
    if url[/^https:/] && !url[/:443/]
      url = url.sub(/https:\/\/([^\/]+|$)(.*)/) { "https://#{$1}:443#{$2}" }
    end
    proxy.stub(url, method: 'post').and_return(
      headers: response[:headers], text: response[:content])
  end
end
```


Then in my tests, I call:

```ruby
Billy.stub_cached_post('https://api.stripe.com/v1/tokens', proxy)
Billy.stub_cached_post('https://m.stripe.com/4', proxy)
```

Have tested while turning off my internet connection, and now my tests are only replaying the cached requests.

Surely there is a better way to cache post requests? I'd really love to use puffing-billy as a proper `VCR` for the front-end, but it seems quite limited at the moment.

**Comment by ndbroadbent** [comment]
Wow, ignore my previous message. I finally figured out how to get `merge_cached_responses_whitelist` to work:

```
  config.merge_cached_responses_whitelist = [
    /api\.stripe\.com(:443)*\/v1\/tokens/,
    /m\.stripe\.com(:443)*\/4/
  ]
```

The key is that you can't include `https:\/\/`, otherwise the rule doesn't match. You must also handle the port `:443` in the URL. After that the cache keys are merged and it only makes a single POST request to each URL. Then you can also have [separate cache directories for each test](https://github.com/oesmith/puffing-billy#separate-cache-directory-for-each-test-in-cucumber), and everything is awesome!

**Comment by tansaku** [comment]
I think we moved to forcing everyone on to the en_US locale - not ideal ..., but we did set up separate cache directories for each test (as VCR has) and that's hugely helpful all round ...
