### ISSUE TITLE
Errno::ENETUNREACH

### ISSUE THREAD

**Issue by foxtree** [oesmith/puffing-billy#246]
Hi, I see the following error in a Docker-based continuous integration test suite:

![image](https://user-images.githubusercontent.com/3383704/40979287-63f8a4ea-68a3-11e8-8748-24864cc1e2c6.png)

Should the following line also rescue on `Errno::ENETUNREACH` ?

https://github.com/oesmith/puffing-billy/blob/master/lib/billy/proxy.rb#L65

**Comment by ronwsmith** [comment]
Hmm, does puffing-billy seem to work otherwise?  That error makes me think it's not working at all.  While adding that rescue would stop the error, I think there are other issues at play.

**Comment by AlanFoster** [comment]
@foxtree What operating system/ruby version are you on? Adding that to the list of caught exceptions makes sense to me.

I would +1 a pull request to fix this, or I wonder if there's a nicer long-term solution here where instead of catching all known possible network errors that indicate that puffing billy has safely shutdown as expected, there's a simple rescue that can be used instead

**Comment by foxtree** [comment]
The error occurs in the `after(:suite)` hook -- it might be due to a race condition, where requests are still being received from Chrome/ChromeDriver, but the Puffing Billy proxy server has already shut down?


```
An error occurred in an `after(:suite)` hook.
Failure/Error: s = TCPSocket.new(host, port)
```

**Comment by foxtree** [comment]
I opened #247, but I'm not sure what's causing the Travis CI errors...

**Comment by ronwsmith** [comment]
Merged related PR
