### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Novtopro** [oesmith/puffing-billy#291]
<img width="1276" alt="1" src="https://user-images.githubusercontent.com/7251140/84515726-6d620600-acff-11ea-9a2d-8e46b387d350.png">

**Comment by ronwsmith** [comment]
Looks like the issue is within eventmachine.  I'd recommend creating an issue for that gem.

**Comment by momolog** [comment]
@Novtopro I ran into the exact same error and the reason was that my ruby hat been compiled with a different openssl version (1.0.2) than eventmachine (1.1.1).
I fixed this by
1. installing openssl 1.0.2 via `brew install rbenv/tap/openssl@1.0`
2. removing the eventmachine gem via `gem uninstall eventmachine`
3. adding this to my `./.bundle/config`:
    BUNDLE_BUILD__EVENTMACHINE: "--with-cppflags=-I/usr/local/opt/openssl@1.0/include"
4. re-bundling via `bundle install`

Hope this helps somebody.
